to_be_done_homepage:
    path:     /
    defaults: { _controller: ToBeDoneBundle:Tasks:index }

to_be_done_new_task:
    path: /new-task
    defaults: { _controller: ToBeDoneBundle:Tasks:new }
    methods: [POST]

to_be_done_set_done:
    path:     /set-done
    defaults: { _controller: ToBeDoneBundle:Tasks:setDone}
    methods: [POST]

to_be_done_registration:
    path: /register
    defaults: { _controller: ToBeDoneBundle:Registration:register }

login_route:
    path: /login
    defaults: { _controller: ToBeDoneBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

video_list:
    path: /video
    defaults: { _controller: ToBeDoneBundle:Video:list }

video:
    path: /video/{filename}
    defaults: { _controller: ToBeDoneBundle:Video:single }
